---
title: "Manipulation"
author: "Wensky LOUIS-JEAN"
date: '2022-05-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```



```{r}

library(dplyr)
library(readxl)


#################
# 1. Importation des donnees 
#################

url1<-'https://www.brh.ht/wp-content/uploads/agregatsmon.xls'
p1f <- tempfile()
download.file(url1, p1f, mode="wb")
agregatsmon.data <-read_excel(path = p1f, skip = 2)
head(agregatsmon.data) # vizyalize 6 premye liy yo
tail(agregatsmon.data, n = 10) # # vizyalize 10 premye liy yo

# data cleaning
agregatsmon.data <- agregatsmon.data[1:517,] # retire 10 denye liy 

agregatsmon.data <- rename(agregatsmon.data, Date = ...1) 

agregatsmon.data <- agregatsmon.data[-1,] # retire premye liy done a (sak gen deskripsyon yo)


agregatsmon.data$Date <- as.numeric(agregatsmon.data$Date)
# conversion date format charactere -> numerique

sum(is.na(agregatsmon.data$Date)) 
# 17 dates non formatees: 309-320, 360-364

agregatsmon.data$Date <- as.Date(agregatsmon.data$Date, 
                                 origin = "1899-12-30")
# conversion dates format nombre en correct format 
# en prenant 30 Decembre 1899 comme point de depart 

agregatsmon.data$Date # verification pour exact match avec fichier Excel

# Formattage des 17 dates manquantes
# Hint: taper les valeurs en observant le fichier excel 

agregatsmon.data$Date[309] <- "2004-07-01"
agregatsmon.data$Date[310] <- "2004-08-01"
agregatsmon.data$Date[311] <- "2004-09-01"
agregatsmon.data$Date[312] <- "2004-10-01"
agregatsmon.data$Date[313] <- "2004-11-01"
agregatsmon.data$Date[314] <- "2004-12-01"
agregatsmon.data$Date[315] <- "2005-01-01"
agregatsmon.data$Date[316] <- "2005-02-01"
agregatsmon.data$Date[317] <- "2005-03-01"
agregatsmon.data$Date[318] <- "2005-04-01"
agregatsmon.data$Date[319] <- "2005-05-01"
agregatsmon.data$Date[320] <- "2005-06-01"

agregatsmon.data$Date[360] <- "2008-10-01"
agregatsmon.data$Date[361] <- "2008-11-01"
agregatsmon.data$Date[362] <- "2008-12-01"
agregatsmon.data$Date[363] <- "2009-01-01"
agregatsmon.data$Date[364] <- "2009-02-01"

###############
# 2. Filtrer a partir d'Octobre 1990
#################

agregatsmon.data2 <- agregatsmon.data %>% 
  filter(Date >= "1990-10-01")

head(agregatsmon.data2)

###############
# 3. Retirer tous les colonnes inutiles
###########

agregatsmon.data2 <- agregatsmon.data2[,-c(5,9,11,15,20,23,25,30,35,40,42,47,56,79,84)]

head(agregatsmon.data2)

agregatsmon.data3 <- agregatsmon.data2[, c(7,8,36,37)]


agregatsmon.data3 <- agregatsmon.data3 %>% 
  rename(M3 = 'M3...8',
         taux_change = `TAUX DE CHANGE BRH`,
         reserves_depot = "Réserves nettes de changes BRH avec dépôts des BCMs (millions de  $)",
         reserves_systeme = "Réserves nettes de change du système banc.(millions de $)")

agregatsmon.data3 <- agregatsmon.data3 %>% 
  mutate(M3 = as.numeric(M3),
         taux_change = as.numeric(taux_change),
         reserves_depot = as.numeric(reserves_depot),
         reserves_systeme = as.numeric(reserves_systeme))

head(agregatsmon.data3)

################
# 4. Estimer le taux de change a partir de M3 et reserves de change
###############

## 4.1 estimation avec reserves nettes de changes BRH avec depots des BCMs
taux_change_est <- lm(taux_change ~ M3 + reserves_depot, 
                      data = agregatsmon.data3)
summary(taux_change_est)$coef

# taux_change_est = 0.29 + 0.02*M3 - 0.02*reserves_depot


## 4.2 estimation avec reserves nettes de changes du systeme bancaire
taux_change_est2 <- lm(taux_change ~ M3 + reserves_systeme, 
                       data = agregatsmon.data3)
summary(taux_change_est2)$coef

# taux_change_est2 = 1.59 + 0.02*M3 - 0.01*reserves_depot




```

