---
title: "Intra_groupe"
author: "Wensky LOUIS-JEAN"
date: '2022-04-27'
output: html_document
---

# Wensky LOUIS-JEAN
# Hadley Kervens RENE
# Alixandra Lorshely COLAS
# Gardy Stanley JEAN BAPTISTE


```{r,warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(openxlsx)

df <- read.xlsx("WB_HT_DATA.xlsx",startRow = 4)# upload fichier excel
head(df)

# transformation de la base de donnees

df <- df %>% pivot_longer(7:67, names_to = "year", values_to = "n") 
# creation de 2 nouvelles variables
# 1. "year" pour sauvegarder les annees (1960-2020)
# 2. "n" la mesure de chaque indicateur pour chaque annee respective


# Figure 2.4



reserve.ratio <- df %>% 
  filter(Indicator.Name == "Bank liquid reserves to bank assets ratio (%)") %>%
  rename(ratio = n) %>%
  select(year, ratio)

head(reserve.ratio)

reserve.ratio %>% 
  filter(year >= "2000")  %>% 
  mutate(annee = 2000:2020) %>% 
  ggplot(aes(annee, ratio))+
  geom_line(color = "dark green")+
  labs(x = "Années",
       y = "% du PIB",
       title = "Figure 2.4: Ratio des réserves liquides des banques sur leurs actifs (%)")+
  geom_smooth(col = "red", se = F, size = 0.01)+
  geom_vline(xintercept = 2008, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2010, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2015, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2020, linetype = "dotted", color = "red")



# Figure 3.1

pib.data <- df %>%  
  filter(Indicator.Name == "GDP (current US$)") %>%
  rename(PIB = n) %>%
  select(year, PIB)

transferts <- df %>% 
  filter(Indicator.Name == "Personal transfers, receipts (BoP, current US$)") %>% 
  rename(montant.transfert = n) %>% 
  select(montant.transfert)

donnees <- data.frame(c(pib.data, transferts))
head(donnees)

donnees %>% 
  mutate(evolution = montant.transfert / PIB * 100) %>% 
  filter(year >= "2000")  %>% 
  mutate(annee = 2000:2020) %>% 
  ggplot(aes(annee, evolution))+
  geom_line(color = "dark green")+
  labs(x = "Années",
       y = "% du PIB",
       title = "Figure 3.1: Evolution des transferts annuelles (% du PIB)")+
   geom_vline(xintercept = 2008, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2010, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2016, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2019, linetype = "dotted", color = "red")+
  geom_vline(xintercept = 2020, linetype = "dotted", color = "red")




```



# 2e methode

```{r}
df <- read.xlsx("WB_HT_DATA.xlsx",startRow = 4)# upload fichier excel

reserve.ratio <- df %>% 
  filter(Indicator.Name == "Bank liquid reserves to bank assets ratio (%)") %>% 
  select(7:67) %>% 
  as.numeric()

annee <- 1960:2020
annee

data <- data.frame(cbind(annee, reserve.ratio))
data

data %>% 
  filter(annee >= 2000) %>% 
  ggplot(aes(annee, reserve.ratio))+
  geom_line(color = "dark green")+
  labs(x = "Années",
       y = "% du PIB",
       title = "Figure 2.4: Ratio des réserves liquides des banques sur leurs actifs (%)")+
  geom_smooth(col = "red", se = F, size = 0.01)+
  geom_vline(xintercept = 2008, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2010, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2015, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2020, linetype = "dotted", color = "red")


# figure 3.1

pib <- df %>%  
  filter(Indicator.Name == "GDP (current US$)") %>% 
  select(7:67) %>% 
  as.numeric()

pib

transferts <- df %>% 
  filter(Indicator.Name == "Personal transfers, receipts (BoP, current US$)") %>%
  select(7:67) %>% 
  as.numeric

donnees <- data.frame(cbind(annee, pib, transferts))

donnees %>% 
  mutate(evolution = transferts / pib * 100) %>% 
  filter(annee >= 2000)  %>% 
  ggplot(aes(annee, evolution))+
  geom_line(color = "dark green")+
  labs(x = "Années",
       y = "% du PIB",
       title = "Figure 3.1: Evolution des transferts annuelles (% du PIB)")+
   geom_vline(xintercept = 2008, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2010, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2016, linetype = "dotted", color = "red")+
   geom_vline(xintercept = 2019, linetype = "dotted", color = "red")+
  geom_vline(xintercept = 2020, linetype = "dotted", color = "red")



  






```







